### ISSUE TITLE
The model cannot be extended

### ISSUE THREAD

**Issue by navotera** [GranadaORM/Granada#18]
Hello 

I try to extend this model by using this : 
```
// extend default Granada Model ORM
class ORM_Model extends Granada\Model
{

    /**
     * @param int id
     * @param bool array return as
     * @return mixed
     */
    public static function findList(int $id, bool $array = false)
    {
        if (is_null($id)) return false;

        $orm = self::where('id', $id);
        return self::arrayOrObject($array, $orm, $find_many = false);
    }
```

However this seems not work on the child Class : 
```
class RatihAnggaranORM extends ORM_Model
{
    public static $_table = 'some_table';  
    public static function findList()
    {
        $this->find_many();
    }
}

```

Use on : 
```
RatihAnggaranORM::where('status', 1)->findList();
```

This will return the error : 
`Message:  no static findList found or static method 'filter_findList' not defined in RatihAnggaranORM`

I also **try to remove the static keyword on findList()** and it is also not work. 
This code previously works perfect on ParisORM when I extend the parisorm base class. 

Any suggestion is appreciated. 

Thank you.

**Comment by joshbmarshall** [comment]
This should now work as it was the same fix as was for #17 can you let me know if that fixes it for you now?

**Comment by navotera** [comment]
Hi @joshbmarshall 

Thank you for the prompt response. 

After checking, seem like any model from the class should started with **filter_** keyword if not it won't be accessible.  I think this approach is not very good since it force any of class function with filter_function_name. 

My suggestion is if the function **has filter_ keyword** it will use the filter features. If not it should run the function name as it is initiate for the object instance method. 

Thank

**Comment by navotera** [comment]
After we tested it I confirm that the version 2.8.3 is still not fixed for this issue.

**Comment by joshbmarshall** [comment]
Just a question as I think your example code is not quite right as you reference $this inside the static function. Can you confirm that code works with Paris? Or copy another example that does.
With the filter_ keyword it is expecting a $query variable passed to it and expects it to return the $query after modification.

Looking at the findList() func in ORM_Model it looks like it's expecting $id to pass to it and be called statically.

I'm doing some further investigation but if you can answer the above would be great

**Comment by navotera** [comment]
> Just a question as I think your example code is not quite right as you reference $this inside the static function. Can you confirm that code works with Paris? Or copy another example that does.
> With the filter_ keyword it is expecting a $query variable passed to it and expects it to return the $query after modification.
> 
> Looking at the findList() func in ORM_Model it looks like it's expecting $id to pass to it and be called statically.
> 
> I'm doing some further investigation but if you can answer the above would be great

Yes I actually know about this. I just try to add static because the error tells me something like "no static $function_name" as my previous comment. I am not using static keyword on ParisORM extended class.

I also write this line : 
**I also try to remove the static keyword on findList() and it does also not work.**


This is an example of actual code : 
https://pastebin.com/XV9bvZwy

**Comment by joshbmarshall** [comment]
Just went through your code, the Paris code and what is in GranadaORM. Granada works the same as Paris for finding the functions. So I can't see how your example code would have worked in Paris. Also can't see how you would use it normally as without the second parameter, that isn't used, it wont sort.

When you do a ->where('some_col', 3) it returns a Wrapper class. This is not the same class as the Model, so functions are not directly callable. All the where_ and find_ functions are in this Wrapper class. So if you create a function in your Model that takes and makes a call from the wrapper class it can't use $this.

So that's where the filter_ prefixed functions work. It should have been like this for Paris as well from what I can see in the code.
I recommend you try something like this in your Model class:

```php
    public static function filter_findList($query, $column = false, $array = false)
    {
        $column = ($column) ? $column : 'nama';

            if ($array) {
                $query = $query->order_by_desc($column);
            }
		
        return $query->find_many();
    }
```
The $query is the Wrapper model that is passed in and back out.

I still can't see what your findList() function is doing.

Note: Once you run find_many() or find_one() you receive your Model class. So you no longer need to prefix with filter_ they are only required for modifications of the query before results come from the database. So you might only have to make a few changes.

**Comment by navotera** [comment]
Yes, you right, I apologize that sent the wrong code that I still not tested, the function that relies on $this after checking on my code only works on the ORM create() or after it already finds either using find_one or find_many. 

Let just focus on the static class that without the filter keyword : 

such as this : 
 ```
    public static function getList($column = false, $array = false)
    {
        $column = ($column) ? $column : 'nama';

        $orm = self::order_by_asc($column);
        return self::arrayOrObject($array, $orm, $findMany = true);
    }
```
When I access this using Class::getList() it works on  parisorm but not work on this Granada. It works on granda if I add filter_ on that function name. 

Is there any way that it can work directly without any folder *filter_* keyword?

**Comment by joshbmarshall** [comment]
That code works for me on Granada, except I don't know what the arrayOrObject() function is.

Note that is via Class::getList() but not Class::where($x, $y)->getList() as where() returns a Wrapper object not Class

**Comment by navotera** [comment]
I apologize yes, seems like this is work. 

and you are right that it cannot be chaining the later form after called the static function. 
Thank you so much for your help
